import "@/index.css";

import { useCallTool, useToolInfo } from "../helpers.js";

const CATEGORY_CLASS: Record<string, string> = {
  discrimination: "cat-discrim",
  fraud: "cat-fraud",
  "brand-safety": "cat-brand",
  security: "cat-secure",
  gdpr: "cat-gdpr",
  quality: "cat-quality",
};

export default function FreshProbes() {
  const { output, isPending } = useToolInfo<"generate-fresh-probes">();
  const { callTool: regenerate, isPending: isRegenerating } = useCallTool(
    "generate-fresh-probes",
  );

  if (isPending && !output) {
    return (
      <Page>
        <p className="serif-display italic text-ink-mute text-[18px]">
          Claude is generating fresh adversarial probes…
        </p>
      </Page>
    );
  }
  if (!output) return null;

  const caughtCount = output.verdicts.filter(
    (v) => v.decision !== "serve",
  ).length;
  const total = output.verdicts.length;

  return (
    <Page>
      <header className="grid md:grid-cols-[1fr_auto] gap-x-12 gap-y-3 items-end">
        <div>
          <div className="eyebrow flex items-center gap-3">
            <span>Research note · live generation</span>
            <span className="text-rule-2">·</span>
            <SourceTag
              source={output.source}
              errorReason={output.errorReason}
            />
          </div>
          <h1 className="serif-display mt-3 text-[clamp(1.8rem,3.5vw,2.6rem)] font-medium leading-[1.05] text-ink">
            Three fresh probes against the gate.
          </h1>
          <p className="serif-display italic mt-3 text-[16px] text-ink-mute leading-snug max-w-[52ch]">
            Generated by Claude this run, scored by the live policy gate.
            Different every time. Run it yourself from the repo.
          </p>
        </div>
        <div
          className="serif-display text-[64px] md:text-[88px] leading-none font-medium tabular-nums text-crimson"
          style={{ fontVariationSettings: '"opsz" 144' }}
        >
          {caughtCount}
          <span className="text-rule-2 mx-0.5">/</span>
          <span className="text-ink-mute">{total}</span>
        </div>
      </header>

      <ol className="flex flex-col rule-top pt-6">
        {output.probes.map((probe, i) => {
          const verdict = output.verdicts[i];
          return (
            <ProbeRow
              key={`${probe.label}-${i}`}
              index={i + 1}
              label={probe.label}
              category={probe.category}
              attackPayload={probe.attackPayload}
              expectedReason={probe.expectedReason}
              decision={verdict.decision}
              gateReasons={verdict.reasons}
              citation={verdict.citation}
            />
          );
        })}
      </ol>

      <footer className="flex flex-wrap items-center justify-between gap-4 rule-top pt-5 text-[12px]">
        <p className="serif-display italic text-ink-mute max-w-[52ch]">
          Q&A defence: hand the judges the repo URL. They hit{" "}
          <span className="font-mono not-italic text-[11px]">
            generate-fresh-probes
          </span>{" "}
          themselves and watch the gate hold against a brand-new set.
        </p>
        <button
          type="button"
          onClick={() => regenerate({ count: 3 })}
          disabled={isRegenerating}
          className="font-mono text-[11px] uppercase tracking-wider px-3 py-2 bg-ink text-paper rounded-sm hover:bg-ink/90 disabled:opacity-50"
        >
          {isRegenerating ? "claude…" : "regenerate"}
        </button>
      </footer>
    </Page>
  );
}

function Page({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-dotgrid text-ink rounded-2xl border border-rule overflow-hidden">
      <div className="mx-auto max-w-4xl px-8 md:px-12 py-10 md:py-12 flex flex-col gap-8">
        {children}
      </div>
    </div>
  );
}

function SourceTag({
  source,
  errorReason,
}: {
  source: "claude" | "fallback";
  errorReason?: string;
}) {
  if (source === "claude") {
    return (
      <span className="font-mono text-[11px] uppercase tracking-wider text-crimson flex items-center gap-1.5">
        <span className="h-1.5 w-1.5 rounded-full bg-crimson animate-pulse-dot" />
        claude live
      </span>
    );
  }
  return (
    <span
      className="font-mono text-[11px] uppercase tracking-wider text-ink-mute flex items-center gap-1.5"
      title={errorReason}
    >
      <span className="h-1.5 w-1.5 rounded-full bg-ink-mute" />
      fallback set
    </span>
  );
}

function ProbeRow({
  index,
  label,
  category,
  attackPayload,
  expectedReason,
  decision,
  gateReasons,
  citation,
}: {
  index: number;
  label: string;
  category: string;
  attackPayload: string;
  expectedReason: string;
  decision: "serve" | "flag" | "block";
  gateReasons: string[];
  citation?: string;
}) {
  return (
    <li className="grid grid-cols-[28px_1fr_auto] items-baseline gap-x-5 py-5 border-b border-rule animate-fade-up">
      <span className="serif-display text-[16px] font-medium text-ink-mute tabular-nums">
        {String(index).padStart(2, "0")}
      </span>
      <div className="min-w-0">
        <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
          <span className="serif-display text-[20px] font-medium text-ink leading-tight">
            {label}
          </span>
          <span className={`cat-chip ${CATEGORY_CLASS[category] ?? ""}`}>
            {category}
          </span>
        </div>
        <pre className="mt-2 font-mono text-[11px] text-ink-mute leading-relaxed whitespace-pre-wrap break-words max-w-[72ch] bg-paper-2 border border-rule rounded p-2">
          {attackPayload}
        </pre>
        <p className="mt-2 text-[13px] text-ink leading-snug max-w-[64ch]">
          <span className="serif-display italic text-ink-mute">gate · </span>
          {gateReasons[0] ?? expectedReason}
        </p>
        {citation ? (
          <p className="mt-1 text-[11.5px] font-mono text-crimson lowercase">
            {citation}
          </p>
        ) : null}
      </div>
      <Verdict decision={decision} />
    </li>
  );
}

function Verdict({ decision }: { decision: "serve" | "flag" | "block" }) {
  if (decision === "block") {
    return (
      <span className="serif-display italic text-[15px] text-crimson inline-flex items-center gap-1.5 animate-mark-in">
        <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden>
          <path
            d="M3 3 L11 11 M11 3 L3 11"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
          />
        </svg>
        block
      </span>
    );
  }
  if (decision === "flag") {
    return (
      <span className="serif-display italic text-[15px] text-ink inline-flex items-center gap-1.5 animate-mark-in">
        <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden>
          <path
            d="M3 2 L3 12 M3 2 L10 4.5 L3 7"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
        flag
      </span>
    );
  }
  return (
    <span className="serif-display italic text-[15px] text-ink-mute inline-flex items-center gap-1.5 animate-mark-in">
      <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden>
        <path
          d="M3 7.5 L6 10.5 L11 4"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
      serve
    </span>
  );
}
